-- users
ALTER TABLE users
ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS users_id_seq;

ALTER TABLE users
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- refresh_tokens
ALTER TABLE refresh_tokens
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS refresh_tokens_id_seq;

ALTER TABLE refresh_tokens
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- images
ALTER TABLE images
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS images_id_seq;

ALTER TABLE images
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- diaries
ALTER TABLE diaries
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS diaries_id_seq;

ALTER TABLE diaries
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- books
ALTER TABLE books
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS books_id_seq;

ALTER TABLE books
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- quotes
ALTER TABLE quotes
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS quotes_id_seq;

ALTER TABLE quotes
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- emotion_ranges
ALTER TABLE emotion_ranges
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS emotion_ranges_id_seq;

ALTER TABLE emotion_ranges
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- tags
ALTER TABLE tags
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS tags_id_seq;

ALTER TABLE tags
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- daily_recommendations
ALTER TABLE daily_recommendations
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS daily_recommendations_id_seq;

ALTER TABLE daily_recommendations
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;