WITH tag_seed(type, emotion_range_name, label, code, sort_order) AS (
    VALUES
        ('EMOTION', 'SAD', '지쳐있는 순간', 'EXHAUSTED', 1),
        ('EMOTION', 'SAD', '아무것도 하기 싫은 순간', 'UNMOTIVATED', 2),
        ('EMOTION', 'SAD', '눈물이 날 것 같은 순간', 'TEARFUL', 3),
        ('EMOTION', 'SAD', '위축되는 순간', 'WITHDRAWN', 4),
        ('EMOTION', 'SAD', '억울한 마음이 드는 순간', 'WRONGED', 5),
        ('EMOTION', 'SAD', '자책하고 싶은 순간', 'SELF_BLAME', 6),
        ('EMOTION', 'SAD', '포기하고 싶은 순간', 'GIVE_UP', 7),
        ('EMOTION', 'SAD', '한없이 우울한 순간', 'DEPRESSED', 8),
        ('EMOTION', 'SAD', '불안해지는 순간', 'ANXIOUS', 9),
        ('EMOTION', 'SAD', '크게 실망하게 되는 순간', 'DISAPPOINTED', 10),
        ('EMOTION', 'SAD', '앞이 막막한 순간', 'STUCK', 11),
        ('EMOTION', 'SAD', '짜증이 밀려오는 순간', 'IRRITATED', 12),
        ('EMOTION', 'SAD', '서운해지는 순간', 'HURT', 13),
        ('EMOTION', 'SAD', '마음이 공허한 순간', 'EMPTY', 14),
        ('EMOTION', 'SAD', '후회가 밀려오는 순간', 'REGRETFUL', 15),
        ('EMOTION', 'SAD', '신경이 예민해지는 순간', 'SENSITIVE', 16),
        ('EMOTION', 'NORMAL', '심심한 순간', 'BORED', 1),
        ('EMOTION', 'NORMAL', '혼자 있고 싶은 순간', 'WANT_TO_BE_ALONE', 2),
        ('EMOTION', 'NORMAL', '마음이 차분해지는 순간', 'CALM', 3),
        ('EMOTION', 'NORMAL', '멍해지는 순간', 'DAZED', 4),
        ('EMOTION', 'NORMAL', '감정이 무덤덤해지는 순간', 'NUMB', 5),
        ('EMOTION', 'NORMAL', '평온한 순간', 'PEACEFUL', 6),
        ('EMOTION', 'NORMAL', '몸이 나른해지는 순간', 'DROWSY', 7),
        ('EMOTION', 'NORMAL', '생각에 잠기는 순간', 'THOUGHTFUL', 8),
        ('EMOTION', 'NORMAL', '마음이 싱숭생숭한 순간', 'UNSETTLED', 9),
        ('EMOTION', 'NORMAL', '여유가 느껴지는 순간', 'RELAXED', 10),
        ('EMOTION', 'NORMAL', '평범하게 흘러가는 순간', 'ORDINARY', 11),
        ('EMOTION', 'NORMAL', '기분이 애매한 순간', 'AMBIVALENT', 12),
        ('EMOTION', 'NORMAL', '문득 센치해지는 순간', 'SENTIMENTAL', 13),
        ('EMOTION', 'NORMAL', '무난하게 흘러가는 순간', 'UNEVENTFUL', 14),
        ('EMOTION', 'NORMAL', '마음이 너그러워지는 순간', 'GENEROUS', 15),
        ('EMOTION', 'HAPPY', '뿌듯한 순간', 'PROUD', 1),
        ('EMOTION', 'HAPPY', '새로운 걸 시작한 순간', 'NEW_BEGINNING', 2),
        ('EMOTION', 'HAPPY', '기분 좋게 웃은 순간', 'SMILED', 3),
        ('EMOTION', 'HAPPY', '더없이 행복한 순간', 'HAPPY', 4),
        ('EMOTION', 'HAPPY', '신나는 순간', 'EXCITED', 5),
        ('EMOTION', 'HAPPY', '설레는 순간', 'FLUTTERING', 6),
        ('EMOTION', 'HAPPY', '홀가분한 순간', 'LIGHTHEARTED', 7),
        ('EMOTION', 'HAPPY', '짜릿함이 느껴지는 순간', 'THRILLED', 8),
        ('EMOTION', 'HAPPY', '한없이 평화로운 순간', 'SERENE', 9),
        ('EMOTION', 'HAPPY', '감사함이 느껴지는 순간', 'GRATEFUL', 10),
        ('EMOTION', 'HAPPY', '안도하는 순간', 'REASSURED', 11),
        ('EMOTION', 'HAPPY', '충만한 순간', 'FULFILLED', 12),
        ('EMOTION', 'HAPPY', '에너지가 돌고 활기찬 순간', 'ENERGIZED', 13),
        ('EMOTION', 'HAPPY', '감격스러운 순간', 'MOVED', 14),
        ('EMOTION', 'HAPPY', '자신감이 넘치는 순간', 'CONFIDENT', 15),
        ('EMOTION', 'HAPPY', '열정이 타오르는 순간', 'PASSIONATE', 16),
        ('NEED', NULL, '위로가 되는 문장', 'COMFORT', 1),
        ('NEED', NULL, '공감해주는 문장', 'EMPATHY', 2),
        ('NEED', NULL, '마음정리', 'MIND_CLEARING', 3),
        ('NEED', NULL, '관점전환', 'PERSPECTIVE_SHIFT', 4),
        ('NEED', NULL, '용기', 'COURAGE', 5),
        ('NEED', NULL, '자존감 회복', 'SELF_ESTEEM', 6),
        ('NEED', NULL, '내려놓기', 'LETTING_GO', 7),
        ('NEED', NULL, '재시작', 'RESTART', 8),
        ('NEED', NULL, '영감을 주는 문장', 'INSPIRATION', 9),
        ('SITUATION', NULL, '실패/실수', 'FAILURE_MISTAKE', 1),
        ('SITUATION', NULL, '일/커리어', 'WORK_CAREER', 2),
        ('SITUATION', NULL, '관계', 'RELATIONSHIP', 3),
        ('SITUATION', NULL, '친구', 'FRIEND', 4),
        ('SITUATION', NULL, '가족', 'FAMILY', 5),
        ('SITUATION', NULL, '연애', 'ROMANCE', 6),
        ('SITUATION', NULL, '이별', 'BREAKUP', 7),
        ('SITUATION', NULL, '진로/미래', 'FUTURE_CAREER', 8),
        ('SITUATION', NULL, '학업', 'STUDY', 9),
        ('SITUATION', NULL, '번아웃', 'BURNOUT', 10),
        ('SITUATION', NULL, '상실', 'LOSS', 11),
        ('SITUATION', NULL, '비교', 'COMPARISON', 12),
        ('CONTEXT', NULL, '집', 'HOME', 1),
        ('CONTEXT', NULL, '카페', 'CAFE', 2),
        ('CONTEXT', NULL, '길거리', 'STREET', 3),
        ('CONTEXT', NULL, '공원', 'PARK', 4),
        ('CONTEXT', NULL, '강가', 'RIVERSIDE', 5),
        ('CONTEXT', NULL, '바다', 'SEA', 6),
        ('CONTEXT', NULL, '산', 'MOUNTAIN', 7),
        ('CONTEXT', NULL, '회사/학교', 'WORKPLACE_SCHOOL', 8),
        ('CONTEXT', NULL, '지하철/버스', 'TRANSIT', 9),
        ('CONTEXT', NULL, '여행지', 'TRAVEL_DESTINATION', 10),
        ('CONTEXT', NULL, '비', 'RAIN', 11),
        ('CONTEXT', NULL, '맑음', 'SUNNY', 12),
        ('CONTEXT', NULL, '흐림', 'CLOUDY', 13),
        ('CONTEXT', NULL, '눈', 'SNOW', 14),
        ('CONTEXT', NULL, '바람', 'WIND', 15),
        ('CONTEXT', NULL, '아침', 'MORNING', 16),
        ('CONTEXT', NULL, '낮', 'DAYTIME', 17),
        ('CONTEXT', NULL, '저녁', 'EVENING', 18),
        ('CONTEXT', NULL, '밤', 'NIGHT', 19),
        ('CONTEXT', NULL, '새벽', 'DAWN', 20),
        ('CONTEXT', NULL, '잠들기 전', 'BEFORE_SLEEP', 21),
        ('CONTEXT', NULL, '봄', 'SPRING', 22),
        ('CONTEXT', NULL, '여름', 'SUMMER', 23),
        ('CONTEXT', NULL, '가을', 'AUTUMN', 24),
        ('CONTEXT', NULL, '겨울', 'WINTER', 25),
        ('CONTEXT', NULL, '산책', 'WALKING', 26),
        ('CONTEXT', NULL, '출근길', 'COMMUTE_TO_WORK', 27),
        ('CONTEXT', NULL, '퇴근길', 'COMMUTE_HOME', 28),
        ('CONTEXT', NULL, '공부 중', 'STUDYING', 29),
        ('CONTEXT', NULL, '일하는 중', 'WORKING', 30),
        ('CONTEXT', NULL, '쉬는 중', 'RESTING', 31),
        ('CONTEXT', NULL, '혼자 있는 시간', 'ALONE_TIME', 32),
        ('CONTEXT', NULL, '이동 중', 'MOVING', 33),
        ('CONTEXT', NULL, '기다리는 중', 'WAITING', 34),
        ('MOOD', NULL, '담담한', 'PLAIN', 1),
        ('MOOD', NULL, '따뜻한', 'WARM', 2),
        ('MOOD', NULL, '현실적인', 'REALISTIC', 3),
        ('MOOD', NULL, '차분한', 'CALM_TONE', 4),
        ('MOOD', NULL, '잔잔한', 'GENTLE', 5),
        ('MOOD', NULL, '시적인', 'POETIC', 6),
        ('MOOD', NULL, '다정한', 'AFFECTIONATE', 7),
        ('MOOD', NULL, '희망적인', 'HOPEFUL', 8),
        ('MOOD', NULL, '가벼운', 'LIGHT', 9),
        ('ROLE', NULL, '지금 마음을 알아주는 문장', 'EMPATHY', 1),
        ('ROLE', NULL, '생각을 바꿔주는 문장', 'PERSPECTIVE', 2),
        ('ROLE', NULL, '다시 움직이게 하는 문장', 'RECOVERY', 3),
        ('AVOID', NULL, '훈계', 'PREACHY', 1),
        ('AVOID', NULL, '과한 긍정', 'TOO_POSITIVE', 2),
        ('AVOID', NULL, '성공 압박', 'SUCCESS_PRESSURE', 3),
        ('AVOID', NULL, '과한 동기부여', 'TOO_MOTIVATIONAL', 4),
        ('AVOID', NULL, '비난', 'BLAMING', 5),
        ('AVOID', NULL, '비교', 'COMPARISON', 6),
        ('AVOID', NULL, '단정', 'DETERMINISTIC', 7)
)
UPDATE tags
SET
    code = tag_seed.code,
    sort_order = tag_seed.sort_order
FROM tag_seed
WHERE tags.type = tag_seed.type
  AND tags.label = tag_seed.label;

WITH tag_seed(type, emotion_range_name, label, code, sort_order) AS (
    VALUES
        ('NEED', NULL, '마음정리', 'MIND_CLEARING', 3),
        ('NEED', NULL, '관점전환', 'PERSPECTIVE_SHIFT', 4),
        ('NEED', NULL, '용기', 'COURAGE', 5),
        ('NEED', NULL, '자존감 회복', 'SELF_ESTEEM', 6),
        ('NEED', NULL, '내려놓기', 'LETTING_GO', 7),
        ('NEED', NULL, '재시작', 'RESTART', 8),
        ('SITUATION', NULL, '실패/실수', 'FAILURE_MISTAKE', 1),
        ('SITUATION', NULL, '일/커리어', 'WORK_CAREER', 2),
        ('SITUATION', NULL, '관계', 'RELATIONSHIP', 3),
        ('SITUATION', NULL, '친구', 'FRIEND', 4),
        ('SITUATION', NULL, '가족', 'FAMILY', 5),
        ('SITUATION', NULL, '연애', 'ROMANCE', 6),
        ('SITUATION', NULL, '이별', 'BREAKUP', 7),
        ('SITUATION', NULL, '진로/미래', 'FUTURE_CAREER', 8),
        ('SITUATION', NULL, '학업', 'STUDY', 9),
        ('SITUATION', NULL, '번아웃', 'BURNOUT', 10),
        ('SITUATION', NULL, '상실', 'LOSS', 11),
        ('SITUATION', NULL, '비교', 'COMPARISON', 12),
        ('CONTEXT', NULL, '집', 'HOME', 1),
        ('CONTEXT', NULL, '카페', 'CAFE', 2),
        ('CONTEXT', NULL, '길거리', 'STREET', 3),
        ('CONTEXT', NULL, '공원', 'PARK', 4),
        ('CONTEXT', NULL, '강가', 'RIVERSIDE', 5),
        ('CONTEXT', NULL, '바다', 'SEA', 6),
        ('CONTEXT', NULL, '산', 'MOUNTAIN', 7),
        ('CONTEXT', NULL, '회사/학교', 'WORKPLACE_SCHOOL', 8),
        ('CONTEXT', NULL, '지하철/버스', 'TRANSIT', 9),
        ('CONTEXT', NULL, '여행지', 'TRAVEL_DESTINATION', 10),
        ('CONTEXT', NULL, '비', 'RAIN', 11),
        ('CONTEXT', NULL, '맑음', 'SUNNY', 12),
        ('CONTEXT', NULL, '흐림', 'CLOUDY', 13),
        ('CONTEXT', NULL, '눈', 'SNOW', 14),
        ('CONTEXT', NULL, '바람', 'WIND', 15),
        ('CONTEXT', NULL, '아침', 'MORNING', 16),
        ('CONTEXT', NULL, '낮', 'DAYTIME', 17),
        ('CONTEXT', NULL, '저녁', 'EVENING', 18),
        ('CONTEXT', NULL, '밤', 'NIGHT', 19),
        ('CONTEXT', NULL, '새벽', 'DAWN', 20),
        ('CONTEXT', NULL, '잠들기 전', 'BEFORE_SLEEP', 21),
        ('CONTEXT', NULL, '봄', 'SPRING', 22),
        ('CONTEXT', NULL, '여름', 'SUMMER', 23),
        ('CONTEXT', NULL, '가을', 'AUTUMN', 24),
        ('CONTEXT', NULL, '겨울', 'WINTER', 25),
        ('CONTEXT', NULL, '산책', 'WALKING', 26),
        ('CONTEXT', NULL, '출근길', 'COMMUTE_TO_WORK', 27),
        ('CONTEXT', NULL, '퇴근길', 'COMMUTE_HOME', 28),
        ('CONTEXT', NULL, '공부 중', 'STUDYING', 29),
        ('CONTEXT', NULL, '일하는 중', 'WORKING', 30),
        ('CONTEXT', NULL, '쉬는 중', 'RESTING', 31),
        ('CONTEXT', NULL, '혼자 있는 시간', 'ALONE_TIME', 32),
        ('CONTEXT', NULL, '이동 중', 'MOVING', 33),
        ('CONTEXT', NULL, '기다리는 중', 'WAITING', 34),
        ('MOOD', NULL, '담담한', 'PLAIN', 1),
        ('MOOD', NULL, '따뜻한', 'WARM', 2),
        ('MOOD', NULL, '현실적인', 'REALISTIC', 3),
        ('MOOD', NULL, '차분한', 'CALM_TONE', 4),
        ('MOOD', NULL, '잔잔한', 'GENTLE', 5),
        ('MOOD', NULL, '시적인', 'POETIC', 6),
        ('MOOD', NULL, '다정한', 'AFFECTIONATE', 7),
        ('MOOD', NULL, '희망적인', 'HOPEFUL', 8),
        ('MOOD', NULL, '가벼운', 'LIGHT', 9),
        ('ROLE', NULL, '지금 마음을 알아주는 문장', 'EMPATHY', 1),
        ('ROLE', NULL, '생각을 바꿔주는 문장', 'PERSPECTIVE', 2),
        ('ROLE', NULL, '다시 움직이게 하는 문장', 'RECOVERY', 3),
        ('AVOID', NULL, '훈계', 'PREACHY', 1),
        ('AVOID', NULL, '과한 긍정', 'TOO_POSITIVE', 2),
        ('AVOID', NULL, '성공 압박', 'SUCCESS_PRESSURE', 3),
        ('AVOID', NULL, '과한 동기부여', 'TOO_MOTIVATIONAL', 4),
        ('AVOID', NULL, '비난', 'BLAMING', 5),
        ('AVOID', NULL, '비교', 'COMPARISON', 6),
        ('AVOID', NULL, '단정', 'DETERMINISTIC', 7)
)
INSERT INTO tags (emotion_range_id, label, type, code, sort_order)
SELECT
    emotion_ranges.id,
    tag_seed.label,
    tag_seed.type,
    tag_seed.code,
    tag_seed.sort_order
FROM tag_seed
LEFT JOIN emotion_ranges ON emotion_ranges.name = tag_seed.emotion_range_name
WHERE NOT EXISTS (
    SELECT 1
    FROM tags
    WHERE tags.type = tag_seed.type
      AND tags.code = tag_seed.code
);

ALTER TABLE tags
    ALTER COLUMN code SET NOT NULL;
