WITH refined_descriptions(type, code, description) AS (
    VALUES
        ('EMOTION', 'EMOTION_EXHAUSTED', '지치고 버티기 힘든 사람에게 쉬어도 된다는 감각이나 조용한 위로를 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_UNMOTIVATED', '의욕이 낮고 시작하기 어려운 사람에게 부담을 낮추거나 작은 움직임을 도와주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_TEARFUL', '슬픔이나 울컥함이 차오른 사람에게 감정을 인정하고 부드럽게 감싸는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_WITHDRAWN', '위축되고 자신감이 줄어든 사람에게 스스로를 작게 보지 않도록 돕는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_WRONGED', '억울함이나 부당함을 느끼는 사람에게 마음을 알아주거나 차분히 정리하게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_SELF_BLAME', '스스로를 탓하는 사람에게 자기 비난을 멈추고 관점을 돌리게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_GIVE_UP', '그만두고 싶거나 포기하고 싶은 사람에게 다시 이어갈 작은 힘을 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_DEPRESSED', '깊게 가라앉은 마음에 과한 긍정보다 조용한 위로와 온기를 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_ANXIOUS', '걱정과 긴장이 큰 사람에게 마음을 안정시키거나 불안을 낮추는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_DISAPPOINTED', '기대가 무너져 허탈한 사람에게 실망을 받아들이고 다시 바라보게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_STUCK', '앞이 막막하고 방향이 보이지 않는 사람에게 생각을 정리하거나 다음 관점을 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_IRRITATED', '짜증과 날선 감정이 올라온 사람에게 감정을 가라앉히거나 거리를 두게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_HURT', '서운함과 섭섭함이 있는 사람에게 마음을 인정하고 관계 감정을 정리하게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_EMPTY', '마음이 비어 있거나 의미가 흐려진 사람에게 잔잔한 온기나 의미를 회복시키는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_REGRETFUL', '후회가 큰 사람에게 지난 일을 다른 각도로 보거나 자신을 덜 몰아붙이게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_SENSITIVE', '예민하고 긴장된 사람에게 자극을 낮추고 차분함을 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_BORED', '심심함이나 낮은 자극 상태에 가볍게 생각을 열어주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_WANT_TO_BE_ALONE', '혼자 있고 싶은 마음에 조용히 머물거나 자기 시간을 인정하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_CALM', '마음을 차분히 가라앉히고 안정적으로 돌아보게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_DAZED', '멍하고 생각이 비어 있는 상태에 천천히 감각이나 마음을 되찾게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_NUMB', '감정이 무덤덤한 사람에게 억지 감정 표현 없이 담담히 곁에 있는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_PEACEFUL', '평온하고 고요한 마음에 잘 맞는 잔잔하고 안정적인 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_DROWSY', '나른하고 느슨한 상태에 부담 없이 읽히는 부드럽고 가벼운 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_THOUGHTFUL', '생각에 잠기고 자신이나 상황을 돌아보는 마음에 맞는 성찰적 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_UNSETTLED', '마음이 어수선하고 싱숭생숭한 사람에게 감정을 정돈하거나 붙잡아주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_RELAXED', '여유롭고 느긋한 마음에 잘 맞는 넓고 부드러운 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_ORDINARY', '평범한 하루를 담담히 받아들이거나 일상의 의미를 보게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_AMBIVALENT', '좋고 나쁨이 애매한 마음에 감정을 단정하지 않고 열어두는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_SENTIMENTAL', '문득 감성적이고 마음이 움직이는 순간에 어울리는 사색적 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_UNEVENTFUL', '큰 일 없이 무난한 하루에 잔잔한 정리감이나 평이한 위로를 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_GENEROUS', '마음이 부드러워지고 너그러워지는 상태에 잘 맞는 따뜻한 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_PROUD', '스스로 해낸 것을 인정하고 뿌듯함을 느끼게 하는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_NEW_BEGINNING', '새로운 시작, 변화, 익숙한 세계를 벗어나는 마음에 맞는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_SMILED', '기분 좋게 웃거나 작은 즐거움을 느끼는 마음에 가볍고 밝은 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_HAPPY', '충분한 행복과 만족을 느끼는 상태에 잘 맞는 밝고 충만한 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_EXCITED', '신나고 에너지가 올라온 마음에 맞는 활기 있는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_FLUTTERING', '기대와 설렘이 있는 마음에 잘 맞는 가볍고 두근거리는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_LIGHTHEARTED', '부담이 줄고 홀가분한 마음에 잘 맞는 가볍고 산뜻한 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_THRILLED', '짜릿한 성취감이나 강한 생동감이 있는 마음에 맞는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_SERENE', '깊은 평화와 고요함을 느끼는 마음에 맞는 잔잔하고 안정적인 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_GRATEFUL', '고마움과 소중함을 느끼게 하는 따뜻하고 다정한 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_REASSURED', '걱정이 풀리고 안도하는 마음에 안정감을 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_FULFILLED', '마음이 꽉 차고 충만한 상태에 잘 맞는 깊이 있는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_ENERGIZED', '움직일 힘과 활기를 깨우는 문장에 선택한다. 단순 긴장이나 번아웃과 혼동하지 않는다.'),
        ('EMOTION', 'EMOTION_MOVED', '감격이나 깊은 감동을 불러오는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_CONFIDENT', '스스로를 믿고 앞으로 나아갈 수 있다는 자기 확신을 주는 문장에 선택한다.'),
        ('EMOTION', 'EMOTION_PASSIONATE', '목표나 일에 대한 강한 몰입과 열정을 북돋는 문장에 선택한다.'),
        ('NEED', 'NEED_COMFORT', '힘든 마음을 부드럽게 다독이고 안전하게 느끼게 하는 역할. 강한 조언보다 위로가 중심일 때 선택한다.'),
        ('NEED', 'NEED_EMPATHY', '감정을 판단하지 않고 알아주거나 함께 있어주는 역할. 해결보다 인정과 공감이 중심일 때 선택한다.'),
        ('NEED', 'NEED_MIND_CLEARING', '복잡한 감정이나 생각을 차분하게 정돈하는 역할. 조용한 성찰과 마음의 정리가 핵심일 때 선택한다.'),
        ('NEED', 'NEED_PERSPECTIVE_SHIFT', '상황이나 자신을 다른 각도에서 보게 하는 역할. 성찰, 자기 이해, 관점 전환이 핵심일 때 선택한다.'),
        ('NEED', 'NEED_COURAGE', '두려움이나 망설임을 넘어 한 걸음 나아가게 하는 역할. 강요가 아니라 조용한 힘을 줄 때 선택한다.'),
        ('NEED', 'NEED_SELF_ESTEEM', '스스로의 가치와 존중감을 회복하게 하는 역할. 비교나 비난을 낮추고 자기 수용을 돕는 문장에 선택한다.'),
        ('NEED', 'NEED_LETTING_GO', '붙잡고 있던 부담이나 집착을 내려놓게 하는 역할. 멈춤, 수용, 놓아줌이 핵심일 때 선택한다.'),
        ('NEED', 'NEED_RESTART', '멈춘 뒤 다시 시작하거나 새로운 단계로 넘어가게 하는 역할. 새 출발과 다시 나아감이 핵심일 때 선택한다.'),
        ('NEED', 'NEED_INSPIRATION', '새로운 생각, 이미지, 감각을 열어주는 역할. 시적이거나 사유를 확장하는 문장에 선택한다.'),
        ('SITUATION', 'SITUATION_FAILURE_MISTAKE', '실수, 실패, 잘못, 후회가 원문에 구체적으로 드러나는 상황. 성장이나 어려움의 은유만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_WORK_CAREER', '회사, 직장, 업무, 일, 커리어처럼 일하는 환경이나 직업적 책임이 직접 드러나는 상황. 추상적 노력만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_RELATIONSHIP', '사람 사이의 오해, 거리, 소통, 연결, 관계 갈등이 직접 드러나는 상황. 자기 자신과의 추상 관계는 제외한다.'),
        ('SITUATION', 'SITUATION_FRIEND', '친구, 우정, 친구와의 서운함이나 거리감이 직접 드러나는 상황에 선택한다. 일반 관계 표현만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_FAMILY', '가족, 부모, 형제, 가정 안의 감정이나 책임이 직접 드러나는 상황에 선택한다.'),
        ('SITUATION', 'SITUATION_ROMANCE', '연애, 연인, 사랑, 호감처럼 낭만적 관계가 직접 드러나는 상황에 선택한다.'),
        ('SITUATION', 'SITUATION_BREAKUP', '이별, 헤어짐, 멀어짐, 관계의 끝이 직접 드러나는 상황에 선택한다. 단순한 변화나 거리감만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_FUTURE_CAREER', '진로, 미래, 앞날, 커리어, 직업 선택, 선택의 갈림길이 직접 드러나는 상황. 길이나 방향의 은유만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_STUDY', '공부, 시험, 학교, 수업, 학업 부담이 직접 드러나는 상황. 배움이나 성장의 일반적 의미만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_BURNOUT', '지침, 소진, 번아웃, 오래 버팀, 에너지 고갈, 쉬고 싶음이 직접 드러나는 상황. 노력이나 투쟁의 은유만으로는 선택하지 않는다.'),
        ('SITUATION', 'SITUATION_LOSS', '상실, 잃어버림, 부재, 떠나감이 직접 드러나는 상황에 선택한다. 단순한 변화나 그리움만으로는 신중히 선택한다.'),
        ('SITUATION', 'SITUATION_COMPARISON', '남, 타인, 기준, 뒤처짐, 비교 감정이 직접 드러나는 상황. 자기 성찰이나 방향 찾기만으로는 선택하지 않는다.'),
        ('CONTEXT', 'CONTEXT_HOME', '집, 방, 현관, 침대처럼 사적인 생활 공간이 원문에 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_CAFE', '카페, 커피, 테이블처럼 카페 공간이 원문에 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_STREET', '길거리, 거리, 골목, 길 위의 장면이 물리적 장소로 직접 드러날 때 선택한다. 삶의 길 은유만으로는 선택하지 않는다.'),
        ('CONTEXT', 'CONTEXT_PARK', '공원, 벤치, 잔디, 나무가 있는 휴식 공간이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_RIVERSIDE', '강, 강가, 강변, 호수, 물가가 장소로 직접 드러날 때 선택한다. 흐름의 은유만으로는 선택하지 않는다.'),
        ('CONTEXT', 'CONTEXT_SEA', '바다, 해변, 파도, 수평선이 장소로 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_MOUNTAIN', '산, 숲, 능선, 산길처럼 자연 공간이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_WORKPLACE_SCHOOL', '회사, 사무실, 학교, 교실처럼 역할과 책임이 있는 공간이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_TRANSIT', '지하철, 버스, 정류장, 차 안처럼 대중교통 공간이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_TRAVEL_DESTINATION', '여행, 낯선 도시, 숙소, 여행지가 직접 드러날 때 선택한다. 단순한 이동이나 변화만으로는 선택하지 않는다.'),
        ('CONTEXT', 'CONTEXT_RAIN', '비, 빗소리, 장마, 우산처럼 비 오는 날씨가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_SUNNY', '맑음, 햇살, 파란 하늘처럼 밝은 날씨가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_CLOUDY', '흐림, 구름, 흐린 하늘처럼 낮은 채도의 날씨가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_SNOW', '눈, 눈발, 눈 오는 날처럼 겨울 날씨가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_WIND', '바람, 흔들림, 공기의 움직임이 날씨나 장면으로 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_MORNING', '아침, 새 아침, 하루의 시작이 시간대로 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_DAYTIME', '낮, 한낮, 오후처럼 낮 시간대가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_EVENING', '저녁, 해질녘, 노을처럼 하루가 저무는 시간대가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_NIGHT', '밤, 어둠, 달빛처럼 밤 시간대가 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_DAWN', '새벽, 동트기 전, 잠들지 못한 이른 시간이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_BEFORE_SLEEP', '잠들기 전, 이불 속, 하루를 마무리하는 장면이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_SPRING', '봄, 꽃, 새싹처럼 봄 계절감이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_SUMMER', '여름, 더위, 햇볕, 장마처럼 여름 계절감이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_AUTUMN', '가을, 낙엽, 선선함처럼 가을 계절감이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_WINTER', '겨울, 추위, 눈, 찬 공기처럼 겨울 계절감이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_WALKING', '산책, 걷기, 걸음처럼 걷는 활동이 직접 드러날 때 선택한다. 삶의 걸음 은유만으로는 선택하지 않는다.'),
        ('CONTEXT', 'CONTEXT_COMMUTE_TO_WORK', '출근길, 회사로 가는 길, 아침 이동이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_COMMUTE_HOME', '퇴근길, 집으로 돌아가는 길, 하루를 마친 이동이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_STUDYING', '공부 중, 책상, 시험 준비처럼 공부 활동이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_WORKING', '일하는 중, 업무, 작업, 회의처럼 일하는 활동이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_RESTING', '쉬는 중, 휴식, 잠시 멈춤처럼 쉬는 활동이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_ALONE_TIME', '혼자 있는 시간, 홀로 있음, 혼자만의 방처럼 고립이 아닌 자기 시간이 직접 드러날 때 선택한다.'),
        ('CONTEXT', 'CONTEXT_MOVING', '이동 중, 차 안, 길을 오가는 장면이 직접 드러날 때 선택한다. 인생의 이동 은유만으로는 선택하지 않는다.'),
        ('CONTEXT', 'CONTEXT_WAITING', '기다림, 대기, 기다리는 중이라는 시간 상태가 직접 드러날 때 선택한다.'),
        ('MOOD', 'MOOD_PLAIN', '감정을 과장하지 않고 담담하게 말하는 톤. 조용한 성찰이나 절제된 문장에 선택한다.'),
        ('MOOD', 'MOOD_WARM', '온기 있고 부드럽게 마음을 감싸는 톤. 위로와 다정함이 핵심일 때 선택한다.'),
        ('MOOD', 'MOOD_REALISTIC', '막연한 위로보다 실제적이고 또렷한 관점을 주는 톤. 현실을 직시하되 밀어붙이지 않을 때 선택한다.'),
        ('MOOD', 'MOOD_CALM_TONE', '긴장을 낮추고 안정적으로 가라앉히는 톤. 차분한 정리와 성찰에 선택한다.'),
        ('MOOD', 'MOOD_GENTLE', '세지 않고 은은하게 마음에 남는 톤. 잔잔한 여운과 부드러운 사유에 선택한다.'),
        ('MOOD', 'MOOD_POETIC', '비유, 이미지, 상징이 살아 있는 문학적 톤. 장면성이나 감각이 두드러질 때 선택한다.'),
        ('MOOD', 'MOOD_AFFECTIONATE', '가깝고 친절하게 말을 건네는 톤. 다정한 호명이나 관계적 온기가 있을 때 선택한다.'),
        ('MOOD', 'MOOD_HOPEFUL', '앞으로 나아갈 가능성과 빛을 보여주는 톤. 과한 긍정이 아니라 조용한 희망일 때 선택한다.'),
        ('MOOD', 'MOOD_LIGHT', '부담이 적고 산뜻하게 읽히는 톤. 무겁지 않은 위로나 짧은 환기에 선택한다.'),
        ('ROLE', 'ROLE_EMPATHY', '추천 결과에서 감정을 인정하고 지금 마음을 알아주는 대표 역할. 해결보다 공감이 중심인 문장에 선택한다.'),
        ('ROLE', 'ROLE_PERSPECTIVE', '추천 결과에서 생각을 바꾸거나 마음을 정리하게 하는 대표 역할. 성찰과 관점 전환이 중심인 문장에 선택한다.'),
        ('ROLE', 'ROLE_RECOVERY', '추천 결과에서 다시 움직이거나 새로 시작하게 하는 대표 역할. 용기, 재시작, 회복의 힘이 중심인 문장에 선택한다.'),
        ('AVOID', 'AVOID_PREACHY', '해야 한다, 하지 마라, 반드시, 옳다/그르다처럼 가르치거나 명령하는 표현이 직접 있는 경우에만 선택한다.'),
        ('AVOID', 'AVOID_TOO_POSITIVE', '어려움을 인정하지 않고 다 괜찮다, 무조건 잘된다처럼 지나치게 낙관하는 표현이 직접 있는 경우에만 선택한다.'),
        ('AVOID', 'AVOID_SUCCESS_PRESSURE', '성공, 성과, 이겨야 함, 최고가 되어야 함처럼 성취 압박이 직접 드러나는 경우에만 선택한다.'),
        ('AVOID', 'AVOID_TOO_MOTIVATIONAL', '당장 해내라, 무조건 움직여라, 포기하지 말고 버텨라처럼 행동을 강하게 밀어붙이는 표현이 직접 있는 경우에만 선택한다.'),
        ('AVOID', 'AVOID_BLAMING', '네 탓, 잘못, 책임, 비난처럼 사용자나 타인을 탓하는 표현이 직접 있는 경우에만 선택한다.'),
        ('AVOID', 'AVOID_COMPARISON', '남들보다, 누구보다, 비교, 뒤처짐처럼 타인과 비교하는 표현이 직접 있는 경우에만 선택한다.'),
        ('AVOID', 'AVOID_DETERMINISTIC', '항상, 절대, 반드시, 결국처럼 감정이나 상황을 단정하는 표현이 직접 있는 경우에만 선택한다.')
)
UPDATE tags
SET description = refined_descriptions.description
FROM refined_descriptions
WHERE tags.type = refined_descriptions.type
  AND tags.code = refined_descriptions.code;
