ALTER TABLE IF EXISTS recommendation_quotes
    ADD COLUMN IF NOT EXISTS candidate_source VARCHAR(40),
    ADD COLUMN IF NOT EXISTS need_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS emotion_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS context_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS situation_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS mood_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS metadata_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS semantic_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS final_score DOUBLE PRECISION;
