spring:

  application:
    name: app

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
