name: CI

on:
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CONFIG_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: 빌드 및 테스트
        run: ./gradlew clean build
